### ISSUE TITLE
Kitty base-16 color template doesn't match specs

### ISSUE THREAD

**Issue by psynyde** [tinted-theming/tinted-kitty#3]
Hi,
I went through tinted-theming base-16 [style guide](https://github.com/tinted-theming/home/blob/main/styling.md) and kitty [color table](https://sw.kovidgoyal.net/kitty/conf/#the-color-table) and looks like bright colors from `template/base16.mustache` doesn't follow the specs.
for example:
```mustache
color8 #{{base03-hex}}
color9 #{{base09-hex}} -- orange instead of bright red
color10 #{{base01-hex}} -- black instead of light green
color11 #{{base02-hex}} -- light black instead of yellow
color12 #{{base04-hex}} -- gray instead of blue
color13 #{{base06-hex}} -- foreground (white) instead of magenta
color14 #{{base0F-hex}} -- dark red instead of cyan
color15 #{{base07-hex}}
```
I believe the issue in danth/stylix#567 is also caused by this.

**Comment by JamyGolden** [comment]
Thanks for the issue. I've just created a PR to fix this: https://github.com/tinted-theming/tinted-kitty/pull/4

I'll merge it in a day or so if there is no discussion around it

**Comment by JamyGolden** [comment]
Just merged.
